name: mestrado-cuda

services:

  # --------------------------------------------------------------------------------------
  # --- BUN + WHISPERX DEV                                                              ---
  # --------------------------------------------------------------------------------------

  app:
    container_name: bun-app
    build:
      context: .
      dockerfile: cuda.containerfile
    working_dir: /app
    volumes:
      - ./:/app:Z,U
      - ./.data/videos:/videos:Z,U
    restart: unless-stopped
    ports:
      - "3000:3000"    
    security_opt:
      - label=disable
    devices:
      - nvidia.com/gpu=all
    command:
      bun dev
      # sleep infinity

  # --------------------------------------------------------------------------------------
  # --- Postgres                                                                       ---
  # --------------------------------------------------------------------------------------

  postgres:
    container_name: 
      postgres
    image: 
      docker.io/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql:Z,U
    restart: unless-stopped

  # --------------------------------------------------------------------------------------
  # --- ADMINER                                                                        ---
  # --------------------------------------------------------------------------------------

  # adminer:    
  #   image: docker.io/adminer:latest
  #   container_name: adminer
  #   restart: unless-stopped
  #   environment:
  #     ADMINER_DEFAULT_SERVER: postgres
  #   ports:
  #     - "5050:8080"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./.data/adminer_data:/var/lib/adminer:Z,U
  #   restart: unless-stopped

  # --------------------------------------------------------------------------------------
  # --- ELASTIC SEARCH                                                                 ---
  # --------------------------------------------------------------------------------------

  elasticsearch:
    image: docker.io/elasticsearch:9.1.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data:Z,U
    restart: unless-stopped


  # --------------------------------------------------------------------------------------
  # --- LiteLLM                                                                       ---
  # --------------------------------------------------------------------------------------

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm
    command:
      - "--config"
      - "/app/config.yaml"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml:Z
    restart: unless-stopped
    ports:
      - "4000:4000"
    depends_on:
      - ollama

  # --------------------------------------------------------------------------------------
  # --- OLLAMA                                                                        ---
  # --------------------------------------------------------------------------------------

  ollama:
    image: docker.io/ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.data/ollama:/root/.ollama:Z,U
    restart: unless-stopped
    security_opt:
      - label=disable
    devices:
      - nvidia.com/gpu=all