model_list:
  - model_name: chat-z1
    litellm_params:
      model: ollama/llama3.2:3b
      api_base: http://ollama:11434

  - model_name: chat-z2
    litellm_params:
      model: ollama/qwen3:4b
      api_base: http://ollama:11434

  - model_name: chat-z3
    litellm_params:
      model: ollama/qwen2.5:3b
      api_base: http://ollama:11434

  - model_name: chat-z4
    litellm_params:
      model: ollama/phi3:mini
      api_base: http://ollama:11434

  - model_name: chat
    litellm_params:
      model: gemini/gemini-3.5-flash-lite
      api_key: os.environ/GEMINI_API_KEY