name: mestrado-prod

services:

  # --------------------------------------------------------------------------------------
  # --- BUN + WHISPER DEV                                                              ---
  # --------------------------------------------------------------------------------------

  app:
    container_name: 
      prod-bun-app
    build:
      context: .
      dockerfile: slim.containerfile
    working_dir: /app
    volumes:
      - ./app:/app:Z,U
    restart: unless-stopped
    ports:
      - "3000:3000"
    command:
      bun dev

  # --------------------------------------------------------------------------------------
  # --- Postgres                                                                       ---
  # --------------------------------------------------------------------------------------

  postgres:
    container_name: 
      prod-postgres
    image: 
      docker.io/postgres:latest
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./.data/postgres_data:/var/lib/postgresql:Z,U
    restart: unless-stopped

  # --------------------------------------------------------------------------------------
  # --- ELASTIC SEARCH                                                                 ---
  # --------------------------------------------------------------------------------------

  elasticsearch:
    image: docker.io/elasticsearch:9.1.0
    container_name: 
      prod-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    expose:
      - "9200"
    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data:Z,U
    restart: unless-stopped


  # --------------------------------------------------------------------------------------
  # --- LiteLLM                                                                       ---
  # --------------------------------------------------------------------------------------

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: 
      prod-litellm
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    command:
      - "--config"
      - "/app/config.yaml"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml:Z,U
    restart: unless-stopped
    expose:
      - "4000"

  # --------------------------------------------------------------------------------------
  # --- OLLAMA                                                                        ---
  # --------------------------------------------------------------------------------------

  # ollama:
  #   image: docker.io/ollama/ollama:latest
  #   container_name: 
  #     prod-ollama
  #   ports:
  #     - "11434"
  #   volumes:
  #     - ./.data/ollama:/root/.ollama:Z,U
  #   restart: unless-stopped